### ISSUE TITLE
can I generate  HTS Label by only txt file not wav ?

### ISSUE THREAD

**Issue by wann31828** [Jackiexiao/MTTS#3]
excuse me  , I have a question of this frontend , 

If I have a chinese txt file and I want to use this frontend to generate its HTS label ,
do I have to generate a wav file of it by other TTS first ? 
is there a way to generate labels of target txt file without its corresponding wav file?

thanks

**Comment by coldsheep-AILabs** [comment]
Yes, you can~
Check out `src/mandarin_frontend.py` and test with:
`python3 mandarin_frontend.py`

The output will be printed in following format:
`0 0 xx^xx-sil+c=e4@/A:xx-xx^xx@/B:xx+xx@xx^xx^xx+xx#xx-xx-/C:xx_xx^xx#xx+xx+xx&/D:xx=xx!xx@xx-xx&/E:xx|xx-xx@xx#xx&xx!xx-xx#/F:xx^xx=xx_xx-xx!
0 0 xx^sil-c+e4=sh@/A:xx-4^4@/B:0+0@1^2^1+1#1-1-/C:xx_v^m#xx+0+0&/D:xx=1!xx@1-1&/E:xx|1-xx@xx#1&xx!1-1#/F:xx^1=3_1-1!
...`

Then you can write this into a prompt-lab file for wav synthesize.

**Comment by wann31828** [comment]
great ! 
thank you

**Comment by v-yunbin** [comment]
@coldsheep-AILabs whether no time stamp in lab file will have some effect on decode result?

**Comment by coldsheep-AILabs** [comment]
@v-yunbin Hmm.. I guess you mean synthesize wav files?

In merlin TTS, you need a duration model to predict those timestamp of each phone in synthesize phase, before passing it to acoustic model and generate the final wav.

Therefore, if your lab file has corresponding speech utterance already, the generated wav will be different with the original one because the two models won't predict 100% the same with your original human-speaking file (both timestamps and acoustic parameters).

**Comment by v-yunbin** [comment]
@Jackiexiao synthetic speech pacing is very fast, do you think what is the reason? duration model ？

**Comment by Jackiexiao** [comment]
I haven't further thought about this problem yet. Currently, I just replace punctuation mark with pau or silence
